[project]
name = "docsem"
version = "0.1.0"
license = "MIT"
license-files = ["LICENSE"]
description = "A python module that converts input documents into Standardized Representations"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "azure-ai-formrecognizer>=3.3.3",
    "azure-core>=1.41.0",
    "dotenv>=0.9.9",
]

[project.scripts]
generate = "docsem.cli:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"
